In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv("../data/plot_data/test_ari.csv")
df

,pre,pre_std,emb,emb_std,rec,rec_std,origional,origional_std,stage
0,0.055588,0.221194,0.000738,0.003637,6.217957e-04,0.004831,0.028975,0.115490,pre
1,0.000876,0.004011,0.013633,0.062399,4.283930e-05,0.000739,0.000476,0.002244,emb
2,0.000476,0.004547,0.000036,0.001016,4.358707e-03,0.051063,0.000019,0.000462,rec
3,0.000419,0.013403,0.000016,0.000510,4.384265e-08,0.000001,0.000977,0.031235,origional

In [5]:
data = np.zeros((4, 4))
data = df[['pre', 'emb', 'rec', 'origional']] 
data

        pre       emb           rec  origional
0  0.055588  0.000738  6.217957e-04   0.028975
1  0.000876  0.013633  4.283930e-05   0.000476
2  0.000476  0.000036  4.358707e-03   0.000019
3  0.000419  0.000016  4.384265e-08   0.000977