In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import distinctipy as dpy

import sys
import os

parent_dir = os.path.abspath(os.path.join(os.path.abspath(''), os.pardir, os.pardir, os.pardir))
sys.path.append(parent_dir)

from vae import FluxVAE
from misc.vae import load_VAE
from misc.constants import SOURCE_COLUMNS

from sklearn.manifold import TSNE

In [24]:
#kmeans_test_df = pd.read_csv("km_emb_test.csv")
kmeans_df = pd.read_csv("./agren_40_long/km_emb_test.csv")

#emb_test_df = pd.read_csv("a40_embt_test.csv")
emb_df = pd.read_csv("./agren_40_long/emb_tsne_test.csv")

kmeans_df

                            label  kmeans_cluster
0     kidney_-_cells_in_tubules_2              21
1     kidney_-_cells_in_tubules_2              21
2     kidney_-_cells_in_tubules_2              21
3     kidney_-_cells_in_tubules_2              21
4     kidney_-_cells_in_tubules_2              21
...                           ...             ...
8155    heart_muscle_-_myocytes_2              25
8156    heart_muscle_-_myocytes_2              25
8157    heart_muscle_-_myocytes_2              25
8158    heart_muscle_-_myocytes_2              25
8159    heart_muscle_-_myocytes_2              25

[8160 rows x 2 columns]

In [8]:
cell_types =list(emb_df["label"].unique())
cell_colors = np.array(dpy.get_colors(len(cell_types), pastel_factor=0.8))

def tshow(df : pd.DataFrame, ax, label=""):
    colors = cell_colors[df["label_n"]]

    ax.scatter(df["tsne0"], df["tsne1"], s=1, c=colors)
    ax.set_title(label)

In [27]:

emb_df["label_n"] = emb_df["label"].map(cell_types.index)
emb_km_df = emb_df.copy()
emb_km_df["label_n"] = kmeans_df['kmeans_cluster']

emb_df

,tsne0,tsne1,label,file_n,sample_n,file_name,label_n
0,4.067279,-78.145040,kidney_-_cells_in_tubules_2,0,2244,kidney_-_cells_in_tubules_2_5000(5),0
1,5.536230,-83.141080,kidney_-_cells_in_tubules_2,0,2882,kidney_-_cells_in_tubules_2_5000(5),0
2,7.800563,-74.396416,kidney_-_cells_in_tubules_2,0,3235,kidney_-_cells_in_tubules_2_5000(5),0
3,5.229138,-75.731300,kidney_-_cells_in_tubules_2,0,302,kidney_-_cells_in_tubules_2_5000(5),0
4,5.152254,-77.116620,kidney_-_cells_in_tubules_2,0,1921,kidney_-_cells_in_tubules_2_5000(5),0
...,...,...,...,...,...,...,...
8155,-59.117023,-36.448822,heart_muscle_-_myocytes_2,79,2812,heart_muscle_-_myocytes_2_5000(5),11
8156,-54.935050,-33.677097,heart_muscle_-_myocytes_2,79,4608,heart_muscle_-_myocytes_2_5000(5),11
8157,-56.063385,-28.812313,heart_muscle_-_myocytes_2,79,3320,heart_muscle_-_myocytes_2_5000(5),11
8158,-57.121920,-33.631985,heart_muscle_-_myocytes_2,79,634,heart_muscle_-_myocytes_2_5000(5),11
8159,-62.133858,-31.228714,heart_muscle_-_myocytes_2,79,142,heart_muscle_-_myocytes_2_5000(5),11

In [26]:
def find_matched_cluster(k):
    df = emb_df.copy()
    df['matches_k'] = df['label_n'] == k

    index = kmeans_df['kmeans_cluster'] == k
    print(emb_df[index].sum())

find_matched_cluster(1)

KeyError: 'label_n'

In [ ]:

cluster_mapping = {
    k : find_matched_cluster(k)
    for k in kmeans_df['label_n'].unique()
}

print(cluster_mapping)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12,6))

tshow(emb_df, ax1, "Cell Types")
tshow(emb_km_df, ax2, "KMeans")

#fig.savefig("Emb_kmeans.png", dpi=400)